// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-pending-questions.ts
import { createClient } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_pending_questions_default = defineTool({
  name: "list_pending_questions",
  title: "Listar preguntas pendientes",
  description: "Lista las preguntas de Mercado Libre pendientes de respuesta para las empresas del usuario autenticado. Devuelve id, texto, comprador, producto y borrador de IA si existe.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("M\xE1ximo de preguntas a devolver (por defecto 20)."),
    company_id: z.string().uuid().optional().describe("Filtrar por empresa. Si se omite, incluye todas las empresas del usuario.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, company_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("questions").select("id, company_id, product_id, question_text, buyer_nickname, status, ai_suggested_answer, ai_category, requires_human, created_at, products(title, meli_id)").in("status", ["pending", "needs_human", "queued_auto"]).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (company_id) query = query.eq("company_id", company_id);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { questions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-question.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_question_default = defineTool2({
  name: "get_question",
  title: "Ver detalle de pregunta",
  description: "Devuelve el detalle completo de una pregunta por su ID, incluyendo respuesta sugerida por la IA y datos del producto.",
  inputSchema: {
    question_id: z2.string().uuid().describe("ID interno (uuid) de la pregunta.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ question_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    const { data, error } = await supabase.from("questions").select("*, products(title, meli_id, permalink, price)").eq("id", question_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "No encontrada" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { question: data }
    };
  }
});

// src/lib/mcp/tools/answer-question.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var answer_question_default = defineTool3({
  name: "answer_question",
  title: "Responder pregunta en Mercado Libre",
  description: "Publica una respuesta en Mercado Libre para la pregunta indicada, en nombre del usuario autenticado. Es una acci\xF3n irreversible: la respuesta queda visible p\xFAblicamente en la publicaci\xF3n.",
  inputSchema: {
    question_id: z3.string().uuid().describe("ID interno (uuid) de la pregunta a responder."),
    answer_text: z3.string().min(1).max(2e3).describe("Texto de la respuesta (m\xE1x. 2000 caracteres). Debe ser claro y respetuoso.")
  },
  annotations: {
    readOnlyHint: false,
    destructiveHint: false,
    idempotentHint: false,
    openWorldHint: true
  },
  handler: async ({ question_id, answer_text }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const supabase = supabaseForUser3(ctx);
    const { data, error } = await supabase.functions.invoke("publish-meli-answer", {
      body: { question_id, answer_text, source: "mcp" }
    });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? { ok: true }, null, 2) }],
      structuredContent: { result: data }
    };
  }
});

// src/lib/mcp/tools/search-knowledge-base.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^4.4.3";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_knowledge_base_default = defineTool4({
  name: "search_knowledge_base",
  title: "Buscar en base de conocimiento",
  description: "B\xFAsqueda sem\xE1ntica en la base de conocimiento (art\xEDculos indexados con embeddings) de la empresa del usuario. Devuelve los fragmentos m\xE1s relevantes para la consulta.",
  inputSchema: {
    query: z4.string().min(2).describe("Texto de b\xFAsqueda en lenguaje natural."),
    company_id: z4.string().uuid().describe("ID de la empresa donde buscar."),
    limit: z4.number().int().min(1).max(10).optional().describe("M\xE1ximo de fragmentos a devolver (por defecto 5).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, company_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const supabase = supabaseForUser4(ctx);
    const { data, error } = await supabase.functions.invoke("kb-search", {
      body: { query, company_id, limit: limit ?? 5 }
    });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { results: data }
    };
  }
});

// src/lib/mcp/tools/list-companies.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
function supabaseForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_companies_default = defineTool5({
  name: "list_my_companies",
  title: "Listar mis empresas",
  description: "Lista las empresas a las que pertenece el usuario autenticado, con su rol en cada una. \xDAtil como paso previo para obtener el company_id que requieren otras herramientas.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const supabase = supabaseForUser5(ctx);
    const { data, error } = await supabase.from("memberships").select("company_id, role, companies(id, name)").eq("user_id", ctx.getUserId());
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { memberships: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ropbkdqhqdeiwrenrmjt";
var mcp_default = defineMcp({
  name: "soporteml-mcp",
  title: "SoporteML",
  version: "0.1.0",
  instructions: "Herramientas de SoporteML para gestionar preguntas de Mercado Libre. Us\xE1 list_my_companies para descubrir el company_id del usuario, list_pending_questions para ver la bandeja, get_question para el detalle, search_knowledge_base para consultar pol\xEDticas y contenido de la empresa, y answer_question para publicar una respuesta en MeLi (acci\xF3n p\xFAblica e irreversible: confirm\xE1 con el usuario antes de invocarla).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_companies_default, list_pending_questions_default, get_question_default, search_knowledge_base_default, answer_question_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
